server.port=8080

########################################################################################################################
########################################           STAGING             #################################################
########################################################################################################################




########################################################################################################################
########################################           Production          #################################################
########################################################################################################################